### ISSUE TITLE
Error in storegpscoordinate EndPoint

### ISSUE THREAD

**Issue by Agus-Wei** [Agus-Wei/ojt-project-gitworkflow#11]
The API return error when I tried to store the gps coordinate. The error message is
SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "lng" violates not-null constraint
DETAIL: Failing row contains (41, -8.6571190000, null, 7, 2018-06-24 02:51:46, 2018-06-24 02:51:46). (SQL: insert into "gps_locations" ("lat", "client_id", "updated_at", "created_at") values (-8.657119, 7, 2018-06-24 02:51:46, 2018-06-24 02:51:46) returning "id")

-----
Update:
lng index must exist since this field is not null field. Update storeGPSCoordinate method in ApiGPSLocationController to remove unset code

**Comment by Gus-Wibi** [comment]
#12
