### ISSUE TITLE
getgpscoordinatelist endpoint return incorrect data

### ISSUE THREAD

**Issue by Gus-Wei** [Agus-Wei/ojt-project-gitworkflow#9]
When I tried to get the gps coordinate list, it returns incorrect gps coordinates. The data return from API is not filter by client_id provided

![bug-example](https://user-images.githubusercontent.com/20238536/41590524-c55b5aec-73e9-11e8-8d59-a3b904f20041.png)

**Comment by Gus-Wibi** [comment]
branch https://github.com/Agus-Wei/ojt-project-gitworkflow/tree/feature-fix-getgpscoordinatelist-endpoint has been introduced to fix this issue

**Comment by Gus-Wibi** [comment]
PR to fix this issue has been made
#10
